// Expected API paths and arguments, independent of the CLI command registrations.
export const commands = [
  ['tiktok', 'profile', '/api/tiktok/profile', { handle: 'luketriestech' }],
  ['tiktok', 'videos', '/api/tiktok/profile/videos', { handle: 'luketriestech' }],
  ['tiktok', 'video', '/api/tiktok/video', { url: 'https://example.com/post/123?x=one&y=two' }],
  [
    'tiktok',
    'transcript',
    '/api/tiktok/video/transcript',
    { url: 'https://example.com/post/123?x=one&y=two' },
  ],
  [
    'tiktok',
    'comments',
    '/api/tiktok/video/comments',
    { url: 'https://example.com/post/123?x=one&y=two' },
  ],
  ['tiktok', 'creator-transcripts', '/api/tiktok/creator/transcripts', { handle: 'luketriestech' }],
  ['tiktok', 'followers', '/api/tiktok/user/followers', { handle: 'luketriestech' }],
  ['tiktok', 'following', '/api/tiktok/user/following', { handle: 'luketriestech' }],
  ['tiktok', 'live', '/api/tiktok/user/live', { handle: 'luketriestech' }],
  ['tiktok', 'song', '/api/tiktok/song', { clipId: '123' }],
  ['tiktok', 'song-videos', '/api/tiktok/song/videos', { clipId: '123' }],
  ['tiktok', 'search', '/api/tiktok/search/keyword', { query: 'cats + dogs & birds/雪' }],
  ['tiktok', 'users', '/api/tiktok/search/users', { query: 'cats + dogs & birds/雪' }],
  ['tiktok', 'top', '/api/tiktok/search/top', { query: 'cats + dogs & birds/雪' }],
  ['tiktok', 'hashtag', '/api/tiktok/search/hashtag', { hashtag: '123' }],
  ['tiktok', 'popular-creators', '/api/tiktok/creators/popular', {}],
  ['tiktok', 'popular-hashtags', '/api/tiktok/hashtags/popular', {}],
  ['tiktok', 'popular-songs', '/api/tiktok/songs/popular', {}],
  ['tiktok', 'popular-videos', '/api/tiktok/videos/popular', {}],
  ['tiktok', 'trending', '/api/tiktok/get-trending-feed', { region: 'US' }],
  ['instagram', 'profile', '/api/instagram/profile', { handle: '123' }],
  ['instagram', 'basic-profile', '/api/instagram/basic-profile', { userId: '123' }],
  ['instagram', 'posts', '/api/instagram/user/posts', { handle: '123' }],
  ['instagram', 'reels', '/api/instagram/user/reels', { handle: '123' }],
  ['instagram', 'post', '/api/instagram/post', { url: 'https://example.com/post/123?x=one&y=two' }],
  [
    'instagram',
    'comments',
    '/api/instagram/post/comments',
    { url: 'https://example.com/post/123?x=one&y=two' },
  ],
  [
    'instagram',
    'transcript',
    '/api/instagram/media/transcript',
    { url: 'https://example.com/post/123?x=one&y=two' },
  ],
  ['instagram', 'highlights', '/api/instagram/user/highlights', { handle: '123' }],
  ['instagram', 'highlight', '/api/instagram/user/highlight/detail', { id: '123' }],
  ['instagram', 'search-reels', '/api/instagram/reels/search', { query: 'cats + dogs & birds/雪' }],
  ['instagram', 'embed', '/api/instagram/user/embed', { handle: '123' }],
  ['youtube', 'channel', '/api/youtube/channel', { handle: '123' }],
  ['youtube', 'videos', '/api/youtube/channel/videos', { handle: '123' }],
  ['youtube', 'shorts', '/api/youtube/channel/shorts', { handle: '123' }],
  ['youtube', 'video', '/api/youtube/video', { url: 'https://example.com/post/123?x=one&y=two' }],
  [
    'youtube',
    'transcript',
    '/api/youtube/video/transcript',
    { url: 'https://example.com/post/123?x=one&y=two' },
  ],
  [
    'youtube',
    'comments',
    '/api/youtube/video/comments',
    { url: 'https://example.com/post/123?x=one&y=two' },
  ],
  ['youtube', 'search', '/api/youtube/search', { query: 'cats + dogs & birds/雪' }],
  ['youtube', 'search-hashtag', '/api/youtube/search/hashtag', { hashtag: '123' }],
  ['youtube', 'playlist', '/api/youtube/playlist', { playlist_id: '123' }],
  ['youtube', 'trending-shorts', '/api/youtube/shorts/trending', {}],
  [
    'linkedin',
    'profile',
    '/api/linkedin/profile',
    { url: 'https://example.com/post/123?x=one&y=two' },
  ],
  [
    'linkedin',
    'company',
    '/api/linkedin/company',
    { url: 'https://example.com/post/123?x=one&y=two' },
  ],
  [
    'linkedin',
    'company-posts',
    '/api/linkedin/company/posts',
    { url: 'https://example.com/post/123?x=one&y=two' },
  ],
  ['linkedin', 'post', '/api/linkedin/post', { url: 'https://example.com/post/123?x=one&y=two' }],
  ['linkedin', 'ads', '/api/linkedin/ads/search', { keyword: 'cats + dogs & birds/雪' }],
  ['linkedin', 'ad', '/api/linkedin/ad', { url: 'https://example.com/post/123?x=one&y=two' }],
  ['twitter', 'profile', '/api/twitter/profile', { handle: '123' }],
  ['twitter', 'tweet', '/api/twitter/tweet', { url: 'https://example.com/post/123?x=one&y=two' }],
  ['twitter', 'tweets', '/api/twitter/user/tweets', { handle: '123' }],
  [
    'twitter',
    'transcript',
    '/api/twitter/tweet/transcript',
    { url: 'https://example.com/post/123?x=one&y=two' },
  ],
  [
    'twitter',
    'community',
    '/api/twitter/community',
    { url: 'https://example.com/post/123?x=one&y=two' },
  ],
  [
    'twitter',
    'community-tweets',
    '/api/twitter/community/tweets',
    { url: 'https://example.com/post/123?x=one&y=two' },
  ],
  ['reddit', 'search', '/api/reddit/search', { query: 'cats + dogs & birds/雪' }],
  ['reddit', 'subreddit', '/api/reddit/subreddit/details', { subreddit: '123' }],
  ['reddit', 'subreddit-posts', '/api/reddit/subreddit/posts', { subreddit: '123' }],
  [
    'reddit',
    'subreddit-search',
    '/api/reddit/subreddit/search',
    { subreddit: '123', query: 'cats + dogs & birds/雪' },
  ],
  [
    'reddit',
    'comments',
    '/api/reddit/post/comments',
    { url: 'https://example.com/post/123?x=one&y=two' },
  ],
].map(([platform, command, path, query]) => ({
  args: [platform, command, ...Object.values(query)],
  path,
  query,
  required: command === 'trending' ? 0 : Object.keys(query).length,
}))
